version: '3'

services:
  postgres:
    container_name: template-postgres
    image: postgres:13
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: template-dev-user
      POSTGRES_PASSWORD: template-dev-pass
      POSTGRES_DB: template-db
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - template-net

networks:
  template-net:
    external: false
    driver: bridge

volumes:
  postgres-data: {}
